### ISSUE TITLE
Review safety of all functions

### ISSUE THREAD

**Issue by newpavlov** [CraneStation/rust-wasi#8]
Are we sure what all Core API functions can be wrapped in a safe interface?

**Comment by newpavlov** [comment]
I have this question because [`from_raw_fd`](https://doc.rust-lang.org/nightly/std/os/unix/io/trait.FromRawFd.html#tymethod.from_raw_fd) is an `unsafe` function. For example what will happen if user will call `fd_close(25)` and it is a valid file descriptor? Will we get an IO error if we'll try to do something with this FD? Is it guaranteed that FDs are not getting reused?

**Comment by newpavlov** [comment]
>Does that justify unsafe?

I don't know. :)

@RalfJung
Can you help us here?

**Comment by RalfJung** [comment]
That's kind of an arbitrary call that the ecosystem as a whole has to agree on -- both options work, as long as they are done consistently.

But judging from things like https://github.com/rust-lang/rust/issues/39575, Rust seems to be on the side of "messing with other people's file descriptors is unsafe".

**Comment by RalfJung** [comment]
> But it shouldn't cause undefined behavior.

It doesn't cause UB *on its own*, but if other code relies on privacy of its file descriptors, that could then in combination lead to UB. So the question is if we allow other code to assume that its file descriptors are private. And I think we do, with the issue mentioned above (and unsafe `from_raw_fd`) being an indication, but I don't think this has been officially resolved.

**Comment by newpavlov** [comment]
@sunfishcode 
I think we can be conservative and mark all functions `unsafe` except the "obviously" safe: `clock_res_get`, `clock_time_get`, `proc_exit`, `random_get`, `sched_yield`. Other functions can be made safe in a backwards compatible manner after a better model of safety around file descriptors will get worked out.

If you want, I can add these changes to #5.

**Comment by sunfishcode** [comment]
Yes, that'd be great.

Looking forward, clock and random APIs at least will likely move to requiring file descriptors, but until they do, it's fine to leave them safe. It's interesting that access to ambient authorities is aligning with `unsafe`.

**Comment by marmistrz** [comment]
> That's kind of an arbitrary call that the ecosystem as a whole has to agree on -- both options work, as long as they are done consistently.
> 
> But judging from things like [rust-lang/rust#39575](https://github.com/rust-lang/rust/issues/39575), Rust seems to be on the side of "messing with other people's file descriptors is unsafe".

Related: https://users.rust-lang.org/t/when-should-we-mark-our-functions-unsafe/11834/3

**Comment by newpavlov** [comment]
BTW I think it should be fine to remove `unsafe` for "read-only" functions like `fd_prestat_get`, `fd_prestat_dir_name` and probably others. So it may be worth to reopen this issue or create a new one.

**Comment by RalfJung** [comment]
Even read access can still be abstraction-breaking, and abstraction is what we use to tame unsafe in Rust.

We require unsafe code to read from private `Copy` fields of structs in other modules, even though this *could* be made a safe operation. I think we should follow the same line for read access to other potentially private state.

**Comment by newpavlov** [comment]
In v0.8 all functions are now safe, is it intentional? Even if we'll leave FD stuff out, signatures like [this](https://github.com/bytecodealliance/wasi/blob/master/src/lib.rs#L727) are definitely smell trouble in my opinion.

**Comment by sunfishcode** [comment]
@newpavlov Thanks for spotting that -- I've now opened https://github.com/bytecodealliance/wasi/pull/24 to reintroduce the `unsafe` annotations.
