### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gnzlbg** [CraneStation/rust-wasi#9]
Is there a reason this isn't dual-licensed with Apache 2.0 OR MIT ?

**Comment by gnzlbg** [comment]
_I think_ that isn't 100% necessary, but since this crate is pulled by `libstd`, it would simplify things if it would support the same licenses as the Rust runtime.

**Comment by mati865** [comment]
cc https://github.com/rust-lang/rust/pull/63676 which is integrating this crate into `libstd`.

**Comment by newpavlov** [comment]
I license past and future contributions under the dual (Apache-2.0 WITH LLVM-exception) OR MIT licenses, allowing licensees to chose either at their option.

But do we really need the LLVM-exception? Shouldn't be MIT license already compatible with LLVM?

**Comment by gnzlbg** [comment]
> Would (Apache-2.0 WITH LLVM-exception) OR MIT be acceptable? 

Maybe @brson knows?

I'm not a lawyer, so I really have no idea. Triple-licensing it as "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT" would probably work though.

**Comment by newpavlov** [comment]
I license past and future contributions under the (Apache-2.0 WITH LLVM-exception) OR Apache-2.0 OR MIT licenses, allowing licensees to chose any of these at their option.

**Comment by brson** [comment]
FWIW I think Apache-2.0+LLVM exception or MIT is fine for this purpose. With the LLVM exception it's better-licensed than everything else in the runtime.

Adding the MIT license (as has been done) is required for compatibility with GPL 2.0 (this is why Rust is dual licensed). So everything in the Rust runtime must have a non-Apache, BSD/MIT-like license attached to it, with Apache as a bonus.

Personally I lean toward Apache-2.0/BSL-1.0/MIT trilecense over the LLVM exception, but there's definitely something to be said for just copying the LLVM license, since they have lawyers vetting it.

**Comment by brson** [comment]
Oh, I see that it's now trilicensed Apache-2.0/Apache-2.0+LLVM/MIT. I agree that isn't necessary, Apachae-2.0+LLVM/MIT would be fine, but also it's fine, and might have slight advantages, e.g. tooling will understand Apache-2.0 but not the LLVM exception.

**Comment by brson** [comment]
Oh actually, there is a reason to prefer BSL-1.0 over Apache+LLVM - the GPL 2 compatibility. Now, I don't remember _why_ Apache 2.0 is not GPL 2.0 compatible, so caveat, but the Apache+LLVM/MIT license says that "you are allowed to use the runtime exception, unless you are linking to GPL 2 code".

**Comment by tschneidereit** [comment]
> Though perhaps the LLVM exception fixes the GPL 2 problem, or it has since been determined that Apache 2 and GPL 2 are compatible.

The LLVM exception is specifically meant to make Apache 2 GPL 2-compatible. The legal departments of at least two large vendors we talked to see this as valid and thus see just APL 2+LLVM as GPL 2-compatible.

**Comment by tschneidereit** [comment]
Ah, I now see that @sunfishcode made much better points regarding this [over here](https://github.com/rust-lang/rust/issues/63232#issuecomment-526442885).
